# Site settings
title: Plataciland
email:
description: > # this means to ignore newlines until "baseurl:"
  Un fantastico parco avventura. In Calabria, nel cuore dell'Alto Jonio cosentino.
  Tanto diverimento per grandi e piccoli
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.plataciland.it" # the base hostname & protocol for your site

# User setting
owner: Plataciland
email: plataciland@gmail.com
facebook_username: plataciland
twitter_username: plataciland
github_username: plataciland
address:
  - line: "viale dello Sparviero"
  - line: "Plataci, CS 87070"
  # Feel free to add more lines here 
telephone: (+39) 393 65 14 402
copyright: Angelo Basile

# API settings
google_api_key: AIzaSyDegVoAzKUPiptErPhRAQoSXNbTr3IdLs4 

# Build settings
markdown: kramdown
